import { ArrowLeft, Mail, Phone, UsersRound } from "lucide-react";
import { Link } from "wouter";
import { HotelDashboardLayout } from "@/components/HotelDashboardLayout";
import { useLanguage } from "@/contexts/LanguageContext";
import { trpc } from "@/lib/trpc";

export default function AdminGuests() {
  const { language } = useLanguage(); const guests = trpc.hotel.guests.useQuery();
  return <HotelDashboardLayout allowedRoles={["admin"]}><div className="mx-auto max-w-6xl p-3 sm:p-6"><Link href="/admin" className="inline-flex items-center gap-2 text-sm font-semibold text-muted-foreground hover:text-gold"><ArrowLeft className="size-4" />{language === "en" ? "Back to hotel overview" : "ወደ ሆቴል አጠቃላይ ይመለሱ"}</Link><div className="mt-6 flex flex-wrap items-end justify-between gap-4"><div><p className="section-kicker">{language === "en" ? "Guest directory" : "የእንግዶች ማውጫ"}</p><h1 className="mt-3 font-serif text-4xl">{language === "en" ? "Know every arrival." : "እያንዳንዱን መድረስ ይወቁ።"}</h1></div><span className="flex items-center gap-2 rounded-full bg-gold/12 px-4 py-2 text-sm font-bold text-coffee dark:text-gold"><UsersRound className="size-4" />{guests.data?.length ?? 0} {language === "en" ? "guest profiles" : "የእንግዳ መገለጫዎች"}</span></div>{guests.error ? <div className="mt-8 rounded-2xl border border-red-500/25 bg-red-500/8 p-5 text-sm text-red-700 dark:text-red-300">{language === "en" ? "Guest records could not be loaded. Please try again." : "የእንግዳ መዝገቦች ሊጫኑ አልቻሉም። እባክዎ እንደገና ይሞክሩ።"}</div> : <section className="mt-8 overflow-hidden rounded-3xl border border-foreground/10 bg-card">{guests.isLoading ? <div className="space-y-3 p-6">{Array.from({ length: 3 }).map((_, i) => <div key={i} className="h-20 animate-pulse rounded-2xl bg-muted" />)}</div> : guests.data?.length ? <div className="divide-y divide-foreground/8">{guests.data.map((guest) => <article key={guest.id} className="grid gap-4 p-5 sm:grid-cols-[1fr_1fr_auto] sm:items-center"><div><p className="font-semibold">{guest.name || (language === "en" ? "Guest" : "እንግዳ")}</p><p className="mt-1 flex items-center gap-2 text-sm text-muted-foreground"><Mail className="size-4 text-gold" />{guest.email || "—"}</p></div><div><p className="flex items-center gap-2 text-sm text-muted-foreground"><Phone className="size-4 text-gold" />{guest.phone || (language === "en" ? "No mobile number" : "የሞባይል ቁጥር የለም")}</p><p className="mt-1 text-xs text-muted-foreground">{guest.nationality || "—"} · {guest.language === "am" ? "አማርኛ" : "English"}</p></div><p className="text-xs text-muted-foreground">{language === "en" ? "Last active" : "መጨረሻ ጊዜ"}<br /><strong className="text-foreground">{new Date(guest.lastSignedIn).toLocaleDateString()}</strong></p></article>)}</div> : <div className="p-10 text-center"><p className="font-serif text-xl">{language === "en" ? "Guest profiles will appear here." : "የእንግዳ መገለጫዎች እዚህ ይታያሉ።"}</p><p className="mt-2 text-sm text-muted-foreground">{language === "en" ? "Profiles are created when signed-in guests save their contact preferences." : "የተገቡ እንግዶች የግንኙነት ምርጫዎቻቸውን ሲያስቀምጡ መገለጫዎች ይፈጠራሉ።"}</p></div>}</section>}</div></HotelDashboardLayout>;
}
