import { Activity, Boxes, Database, ShieldCheck } from "lucide-react";
import { HotelDashboardLayout } from "@/components/HotelDashboardLayout";
import { trpc } from "@/lib/trpc";
import { useLanguage } from "@/contexts/LanguageContext";

export default function DeveloperDashboard() {
  const { language } = useLanguage();
  const { data } = trpc.hotel.developerOverview.useQuery();
  return <HotelDashboardLayout allowedRoles={["developer"]}><div className="mx-auto max-w-6xl p-3 sm:p-6"><p className="section-kicker">Mihrat Ashenafi · developer</p><h1 className="mt-3 font-serif text-4xl">{language === "en" ? "Build clarity into every stay." : "በእያንዳንዱ ቆይታ ውስጥ ግልጽነትን ይገንቡ።"}</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-muted-foreground">{language === "en" ? "A focused platform overview for the product creator, with system modules and operational health in view." : "ለምርቱ ፈጣሪ የተዘጋጀ የሥርዓት ሞጁሎችን እና የሥራ ጤናን የሚያሳይ የተኮረ የመድረክ እይታ።"}</p><div className="mt-8 grid gap-4 md:grid-cols-4"><Card icon={Activity} label={language === "en" ? "System health" : "የሥርዓት ጤና"} value={data?.health ?? "checking"} /><Card icon={Boxes} label={language === "en" ? "Active modules" : "ንቁ ሞጁሎች"} value={String(data?.modules ?? "—")} /><Card icon={Database} label={language === "en" ? "Persisted rooms" : "የተቀመጡ ክፍሎች"} value={String(data?.rooms ?? "—")} /><Card icon={ShieldCheck} label={language === "en" ? "Role controls" : "የሚና ቁጥጥሮች"} value="Active" /></div><section className="mt-8 rounded-3xl border border-foreground/10 bg-card p-6"><h2 className="font-serif text-2xl">{language === "en" ? "Platform map" : "የመድረክ ካርታ"}</h2><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{["Public discovery", "Availability", "Reservations", "Room operations", "Bilingual CMS", "Role dashboards"].map((item, index) => <div key={item} className="rounded-2xl bg-accent/55 p-4"><p className="text-xs font-bold text-gold">0{index + 1}</p><p className="mt-2 font-semibold">{item}</p><p className="mt-1 text-xs text-muted-foreground">{language === "en" ? "Connected and ready to evolve" : "የተገናኘ እና ለእድገት ዝግጁ"}</p></div>)}</div></section></div></HotelDashboardLayout>;
}
function Card({ icon: Icon, label, value }: { icon: typeof Activity; label: string; value: string }) { return <article className="rounded-3xl border border-foreground/10 bg-card p-5"><Icon className="size-5 text-gold" /><p className="mt-5 text-2xl capitalize">{value}</p><p className="mt-1 text-sm text-muted-foreground">{label}</p></article>; }
