import { BedDouble, ChevronRight, UsersRound } from "lucide-react";
import { Link } from "wouter";
import { SiteHeader } from "@/components/SiteHeader";
import { trpc } from "@/lib/trpc";
import { useLanguage } from "@/contexts/LanguageContext";

function birr(value: number) { return new Intl.NumberFormat("en-ET").format(value); }

export default function Rooms() {
  const { language } = useLanguage();
  const { data: rooms, isLoading } = trpc.hotel.rooms.useQuery();
  return <div className="min-h-screen bg-background"><SiteHeader /><main className="container py-12 sm:py-20"><div className="grid gap-8 lg:grid-cols-[0.85fr_1.15fr] lg:items-end"><div><p className="section-kicker">{language === "en" ? "Sleep, considered" : "የታሰበ እንቅልፍ"}</p><h1 className="mt-4 max-w-xl font-serif text-5xl leading-[0.94] sm:text-6xl">{language === "en" ? "Rooms with a sense of place." : "ቦታን የሚገልጹ ክፍሎች።"}</h1></div><p className="max-w-xl text-base leading-7 text-muted-foreground">{language === "en" ? "Each room brings together material warmth, thoughtful comfort, and a view into the everyday beauty of Ethiopia." : "እያንዳንዱ ክፍል የቁሳቁስ ሙቀትን፣ በጥንቃቄ የተመረጠ ምቾትን እና የኢትዮጵያን ዕለታዊ ውበት ይዟል።"}</p></div><div className="mt-12 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{isLoading ? Array.from({ length: 3 }).map((_, i) => <div key={i} className="h-80 animate-pulse rounded-3xl bg-muted" />) : rooms?.map((room) => <article key={room.id} className="group overflow-hidden rounded-3xl border border-foreground/9 bg-card shadow-sm transition duration-300 hover:-translate-y-1 hover:shadow-xl"><div className="relative h-48 overflow-hidden bg-[radial-gradient(circle_at_30%_20%,#c9902c_0%,#5a3023_42%,#23140f_100%)]"><div className="absolute inset-0 pattern-mask opacity-50" /><span className="absolute left-5 top-5 rounded-full bg-background/90 px-3 py-1 text-xs font-bold text-coffee backdrop-blur">{room.status === "available" ? (language === "en" ? "Available" : "ዝግጁ") : room.status}</span><span className="absolute bottom-5 left-5 font-serif text-3xl text-white/90">{room.code}</span></div><div className="p-6"><p className="text-xs font-bold uppercase tracking-[0.2em] text-gold">{room.type}</p><h2 className="mt-3 font-serif text-2xl">{language === "en" ? room.nameEn : room.nameAm}</h2><p className="mt-3 min-h-12 text-sm leading-6 text-muted-foreground">{language === "en" ? room.descriptionEn : room.descriptionAm}</p><div className="mt-5 flex items-center gap-4 border-t border-foreground/8 pt-5 text-xs text-muted-foreground"><span className="flex items-center gap-1.5"><BedDouble className="size-4 text-gold" />{room.bedType}</span><span className="flex items-center gap-1.5"><UsersRound className="size-4 text-gold" />{room.capacity}</span></div><div className="mt-6 flex items-end justify-between"><p><span className="text-xs text-muted-foreground">ETB</span><strong className="ml-1 text-xl">{birr(room.priceNight)}</strong><span className="ml-1 text-xs text-muted-foreground">/ {language === "en" ? "night" : "አዳር"}</span></p><Link href={`/reserve?room=${room.id}`} className="inline-flex items-center gap-1 text-sm font-bold text-coffee transition group-hover:text-gold">{language === "en" ? "Reserve" : "ያስይዙ"}<ChevronRight className="size-4" /></Link></div></div></article>)}</div></main></div>;
}
