import { ArrowLeft, BedDouble, Check, UsersRound } from "lucide-react";
import { Link, useRoute } from "wouter";
import { SiteHeader } from "@/components/SiteHeader";
import { trpc } from "@/lib/trpc";
import { useLanguage } from "@/contexts/LanguageContext";

export default function RoomDetail() {
  const { language } = useLanguage(); const [, params] = useRoute("/rooms/:id"); const id = Number(params?.id); const rooms = trpc.hotel.rooms.useQuery(); const room = rooms.data?.find((item) => item.id === id);
  if (rooms.isLoading) return <div className="min-h-screen bg-background"><SiteHeader /><div className="container py-20"><div className="h-96 animate-pulse rounded-3xl bg-muted" /></div></div>;
  if (!room) return <div className="min-h-screen bg-background"><SiteHeader /><div className="container py-20 text-center"><h1 className="font-serif text-4xl">{language === "en" ? "This room is not available." : "ይህ ክፍል አይገኝም።"}</h1><Link href="/rooms" className="mt-6 inline-flex rounded-full bg-coffee px-5 py-3 font-bold text-white">{language === "en" ? "Browse rooms" : "ክፍሎችን ይመልከቱ"}</Link></div></div>;
  const name = language === "en" ? room.nameEn : room.nameAm; const description = language === "en" ? room.descriptionEn : room.descriptionAm;
  return <div className="min-h-screen bg-background"><SiteHeader /><main className="container py-10 sm:py-16"><Link href="/rooms" className="inline-flex items-center gap-2 text-sm font-bold text-muted-foreground hover:text-gold"><ArrowLeft className="size-4" />{language === "en" ? "All rooms" : "ሁሉም ክፍሎች"}</Link><div className="mt-7 grid gap-8 lg:grid-cols-[1.1fr_0.9fr]"><div className="relative min-h-[440px] overflow-hidden rounded-[2rem] bg-[radial-gradient(circle_at_30%_20%,#d69c35_0%,#663323_40%,#20110d_86%)] p-7 text-white"><div className="absolute inset-0 pattern-mask opacity-35" /><div className="relative flex h-full flex-col justify-between"><span className="w-fit rounded-full bg-white/14 px-3 py-1 text-xs font-bold backdrop-blur">{room.type}</span><div><p className="text-sm text-gold">{room.code}</p><h1 className="mt-2 max-w-lg font-serif text-5xl">{name}</h1></div></div></div><section className="flex flex-col justify-center"><p className="section-kicker">{language === "en" ? "A considered rest" : "በጥንቃቄ የተዘጋጀ ዕረፍት"}</p><h2 className="mt-4 font-serif text-3xl">{language === "en" ? "Room details" : "የክፍል ዝርዝር"}</h2><p className="mt-5 leading-8 text-muted-foreground">{description}</p><div className="mt-7 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-accent/60 p-4"><BedDouble className="size-5 text-gold" /><p className="mt-3 text-sm font-semibold">{room.bedType}</p></div><div className="rounded-2xl bg-accent/60 p-4"><UsersRound className="size-5 text-gold" /><p className="mt-3 text-sm font-semibold">{room.capacity} {language === "en" ? "guests" : "እንግዶች"}</p></div></div><div className="mt-7 rounded-2xl border border-foreground/10 p-5"><p className="font-semibold">{language === "en" ? "Included with your stay" : "ከቆይታዎ ጋር የሚካተቱ"}</p><div className="mt-3 grid gap-2 text-sm text-muted-foreground">{(language === "en" ? ["Breakfast with Ethiopian coffee", "High-speed Wi‑Fi", "Daily room care"] : ["ቁርስ ከኢትዮጵያ ቡና ጋር", "ፈጣን ዋይፋይ", "ዕለታዊ የክፍል እንክብካቤ"]).map((item) => <p key={item} className="flex items-center gap-2"><Check className="size-4 text-gold" />{item}</p>)}</div></div><div className="mt-7 flex items-center justify-between"><p><span className="text-xs text-muted-foreground">ETB</span><strong className="ml-1 text-3xl">{new Intl.NumberFormat("en-ET").format(room.priceNight)}</strong><span className="ml-1 text-sm text-muted-foreground">/ {language === "en" ? "night" : "አዳር"}</span></p><Link href={`/reserve?room=${room.id}`} className="rounded-full bg-gold px-6 py-3 font-bold text-coffee">{language === "en" ? "Reserve" : "ያስይዙ"}</Link></div></section></div></main></div>;
}
